#!/usr/bin/env bash
# Desktop integration for macOS and Linux.
#
# Both platforms launch the Electron binary directly rather than `npm start`,
# so there is no terminal window, no node wrapper process, and the window that
# appears belongs to the app itself.

# Where Electron actually is, per platform.
gs_electron_bin() {
  if [ "$GS_OS" = mac ]; then
    printf '%s' "$ROOT/code/app/node_modules/electron/dist/Electron.app/Contents/MacOS/Electron"
  else
    printf '%s' "$ROOT/code/app/node_modules/electron/dist/electron"
  fi
}

gs_launch_app() {
  local bin; bin="$(gs_electron_bin)"
  [ -x "$bin" ] || gs_die "Electron is missing at $bin - the dependency step did not finish."
  ( cd "$ROOT/code/app" && nohup "$bin" . >/dev/null 2>&1 & ) || true
}

# ============================================================= macOS bundle
#
# A tiny wrapper .app. It is not a packaged distribution - it points at the
# clone - but it makes Grindstone a real citizen of Finder, Spotlight, the
# Dock and Cmd-Tab, which is what "click and run" means on a Mac.
#
# Known limitation: the wrapper execs Electron's own binary, so the menu bar
# and Dock tile take their name and icon from node_modules/electron's bundle,
# not from this one - it may say "Electron". The Finder icon, Spotlight entry
# and double-click behaviour are all correct. Fixing the last bit means real
# packaging (electron-builder), which is the Releases work in REQUIREMENTS.md
# section 6.8, not something an installer can do from a source clone.
gs_mac_make_bundle() {
  local appdir="$1"
  local exe="$appdir/Contents/MacOS/Grindstone"
  rm -rf "$appdir"
  mkdir -p "$appdir/Contents/MacOS" "$appdir/Contents/Resources"

  cat > "$appdir/Contents/Info.plist" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>CFBundleName</key>              <string>Grindstone</string>
  <key>CFBundleDisplayName</key>       <string>Grindstone</string>
  <key>CFBundleIdentifier</key>        <string>com.grindstone.app</string>
  <key>CFBundleVersion</key>           <string>0.1.0</string>
  <key>CFBundleShortVersionString</key><string>0.1.0</string>
  <key>CFBundlePackageType</key>       <string>APPL</string>
  <key>CFBundleExecutable</key>        <string>Grindstone</string>
  <key>CFBundleIconFile</key>          <string>app.icns</string>
  <key>NSHighResolutionCapable</key>   <true/>
  <key>LSMinimumSystemVersion</key>    <string>11.0</string>
</dict>
</plist>
PLIST

  cat > "$exe" <<LAUNCH
#!/bin/sh
# Generated by the Grindstone installer. Points at the clone it was run from.
cd "$ROOT/code/app" || exit 1
exec "$(gs_electron_bin)" .
LAUNCH
  chmod +x "$exe"

  if [ -f "$ROOT/code/assets/branding/app.icns" ]; then
    cp "$ROOT/code/assets/branding/app.icns" "$appdir/Contents/Resources/app.icns"
  fi
  # Nudge Launch Services so the icon and Spotlight entry appear now, not at
  # the next login.
  /usr/bin/touch "$appdir" 2>/dev/null || true
  if [ -x /System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister ]; then
    /System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister \
      -f "$appdir" >/dev/null 2>&1 || true
  fi
}

gs_mac_pin_dock() {
  local appdir="$1"
  command -v defaults >/dev/null 2>&1 || return 1
  # Already there? Adding twice leaves two identical Dock tiles.
  if defaults read com.apple.dock persistent-apps 2>/dev/null | grep -q "$appdir"; then
    gs_log "already in the Dock"
    return 0
  fi
  defaults write com.apple.dock persistent-apps -array-add \
    "<dict><key>tile-data</key><dict><key>file-data</key><dict><key>_CFURLString</key><string>$appdir</string><key>_CFURLStringType</key><integer>0</integer></dict></dict></dict>" \
    2>/dev/null || return 1
  killall Dock 2>/dev/null || true
  return 0
}

gs_mac_shortcuts() {
  local picks="$1"
  local appdir="$HOME/Applications/Grindstone.app"

  if gs_picked apps "$picks" || gs_picked dock "$picks" || gs_picked desktop "$picks"; then
    gs_step "Creating Grindstone.app"
    mkdir -p "$HOME/Applications"
    gs_mac_make_bundle "$appdir"
    gs_log "created $appdir"
  fi
  if gs_picked desktop "$picks"; then
    gs_step "Adding it to the Desktop"
    rm -f "$HOME/Desktop/Grindstone.app"
    ln -s "$appdir" "$HOME/Desktop/Grindstone.app" && gs_log "created ~/Desktop/Grindstone.app"
  fi
  if gs_picked dock "$picks"; then
    gs_step "Keeping it in the Dock"
    if gs_mac_pin_dock "$appdir"; then gs_log "added to the Dock"
    else gs_warn "could not update the Dock - drag $appdir onto it to pin it yourself"; fi
  fi
}

# ============================================================== Linux .desktop
gs_linux_desktop_file() {
  local dest="$1"
  cat > "$dest" <<DESKTOP
[Desktop Entry]
Type=Application
Version=1.0
Name=Grindstone
GenericName=Trading platform
Comment=Browser-style multi-broker trading platform
Exec="$(gs_electron_bin)" "$ROOT/code/app"
Path=$ROOT/code/app
Icon=$ROOT/code/assets/branding/icon-256.png
Terminal=false
Categories=Office;Finance;
StartupNotify=true
StartupWMClass=Grindstone
DESKTOP
  chmod +x "$dest"
}

gs_linux_pin_favourites() {
  command -v gsettings >/dev/null 2>&1 || return 1
  local cur
  cur="$(gsettings get org.gnome.shell favorite-apps 2>/dev/null)" || return 1
  case "$cur" in *grindstone.desktop*) gs_log 'already pinned'; return 0 ;; esac
  # The value is a GVariant array literal: ['a.desktop', 'b.desktop'].
  local new
  if [ "$cur" = "@as []" ] || [ "$cur" = "[]" ]; then
    new="['grindstone.desktop']"
  else
    new="$(printf '%s' "$cur" | sed "s/]$/, 'grindstone.desktop']/")"
  fi
  gsettings set org.gnome.shell favorite-apps "$new" 2>/dev/null || return 1
  return 0
}

gs_linux_shortcuts() {
  local picks="$1"
  local appsdir="$HOME/.local/share/applications"
  local entry="$appsdir/grindstone.desktop"

  if gs_picked apps "$picks" || gs_picked dock "$picks"; then
    gs_step "Adding Grindstone to the applications menu"
    mkdir -p "$appsdir"
    gs_linux_desktop_file "$entry"
    command -v update-desktop-database >/dev/null 2>&1 &&
      update-desktop-database "$appsdir" >/dev/null 2>&1
    gs_log "created $entry"
  fi
  if gs_picked desktop "$picks"; then
    gs_step "Adding a desktop icon"
    local desk="$HOME/Desktop"
    # XDG may have renamed or relocated the desktop folder.
    command -v xdg-user-dir >/dev/null 2>&1 && desk="$(xdg-user-dir DESKTOP 2>/dev/null || printf '%s' "$HOME/Desktop")"
    if [ -d "$desk" ]; then
      gs_linux_desktop_file "$desk/grindstone.desktop"
      # GNOME refuses to run a launcher it does not trust; this is the
      # equivalent of the "Allow launching" right-click item.
      command -v gio >/dev/null 2>&1 &&
        gio set "$desk/grindstone.desktop" metadata::trusted true >/dev/null 2>&1
      gs_log "created $desk/grindstone.desktop"
    else
      gs_warn "no Desktop folder found at $desk - skipped the desktop icon"
    fi
  fi
  if gs_picked dock "$picks"; then
    gs_step "Pinning to the favourites bar"
    if gs_linux_pin_favourites; then gs_log 'pinned'
    else gs_warn 'could not pin automatically - open the app, then right-click its icon and choose "Pin to Dash"'; fi
  fi
}

gs_install_shortcuts() {
  if [ "$GS_OS" = mac ]; then gs_mac_shortcuts "$1"; else gs_linux_shortcuts "$1"; fi
}
