"""Start the unattended recorder at Windows logon. Off unless asked.

WHY A LOGON TRIGGER WITH AN INTERACTIVE TOKEN — and not the obvious
alternatives, each of which fails for a concrete reason:

* **A Windows service** runs as LocalSystem, which **cannot decrypt a
  user-scope DPAPI blob**. The recorder would start reliably and never find
  its key.
* **S4U / "run whether the user is logged on or not"** is documented as having
  no access to encrypted data — the same failure, arrived at differently.
* **The HKCU Run key** has a ~260-character command limit and no restart
  policy, and the paths here are long.

AND TASK SCHEDULER ITSELF MAY BE DENIED. Measured on this machine: an
unelevated `schtasks /create` returns "Access is denied" for every variant —
root folder, subfolder, `/it`, explicit `/ru`. Demanding elevation for a data
recorder is the wrong trade, so registration tries the task first and falls
back to a **Startup-folder launcher**, which needs no admin and still runs at
logon with a full interactive token, which is all DPAPI requires. `status()`
reports which mechanism is actually in place, because their properties differ:
a task can restart on failure; a Startup entry runs once per logon.

The Startup folder lives under roaming `%APPDATA%`, so on a roaming profile the
launcher travels to another machine while the key — deliberately in
non-roaming `%LOCALAPPDATA%` — does not. The recorder handles that exactly as
it handles any unreadable key: it logs that one is needed and exits cleanly,
rather than retrying something no retry can fix.

So the honest promise is **"starts at your Windows logon"**, not "starts with
the PC". A machine rebooted and left at the sign-in screen records nothing,
because nothing can unseal the key until that user signs in. That limit is
inherent to sealing the key to the account rather than to a password, which is
the trade that makes unattended recording safe at all.

A LAUNCHER FILE rather than a bare command, because neither mechanism carries
an environment. `GRINDSTONE_DATA_DIR` decides which store the recorder writes
to, and a launch without it records happily into a second, empty market.db the
app never opens — a failure whose only symptom is data that is not there.
"""
from __future__ import annotations

import os
import subprocess
import sys
from pathlib import Path

from . import syskey
from .db import data_dir
from .logs import LOG

TASK_NAME = "Grindstone Recorder"

#: Windows batch files want CRLF. Built by joining rather than embedded in
#: literals: three separate attempts to write "\r\n" inline through tooling
#: corrupted this file, once into a genuine syntax error.
NL = "\r\n"


def available() -> bool:
    return sys.platform == "win32"


def startup_dir() -> Path:
    return (Path(os.environ.get("APPDATA", Path.home() / "AppData/Roaming"))
            / "Microsoft" / "Windows" / "Start Menu" / "Programs" / "Startup")


def startup_entry() -> Path:
    return startup_dir() / "Grindstone Recorder.cmd"


def launcher_path() -> Path:
    """Beside the key, not inside `data_dir()` — same reasoning as the key
    itself, and it keeps the two pieces of unattended setup together."""
    return syskey.key_dir() / "recorder.cmd"


def _python_exe() -> Path:
    """The interpreter running this process, windowed variant when there is
    one. `pythonw.exe` keeps Python itself from opening a console at logon; it
    is only safe because the recorder logs to a file and never calls print()."""
    exe = Path(sys.executable)
    win = exe.with_name("pythonw.exe")
    return win if win.is_file() else exe


def write_launcher() -> Path:
    code_dir = Path(__file__).resolve().parent.parent   # .../code
    body = NL.join([
        "@echo off",
        "rem Generated by Grindstone. Starts the unattended recorder.",
        "rem The data directory is written in EXPLICITLY: a logon launch",
        "rem inherits no environment, and without it the recorder would open",
        "rem a second, empty market.db that the app never looks at.",
        f'set "GRINDSTONE_DATA_DIR={data_dir()}"',
        f'cd /d "{code_dir}"',
        f'"{_python_exe()}" -m backend.recorder_main',
        "",
    ])
    p = launcher_path()
    p.write_text(body, encoding="utf-8")
    return p


def _schtasks(*args: str) -> subprocess.CompletedProcess:
    # A list, never a shell string: these paths contain spaces and a shell
    # would resplit them.
    return subprocess.run(["schtasks.exe", *args], capture_output=True,
                          text=True, timeout=30)


def status() -> dict:
    if not available():
        return {"supported": False, "registered": False, "method": "",
                "reason": "unattended autostart is Windows-only on this build"}
    task = _schtasks("/query", "/tn", TASK_NAME).returncode == 0
    startup = startup_entry().is_file()
    registered = task or startup
    return {
        "supported": True,
        "registered": registered,
        # Named, not hidden: a scheduled task can restart on failure and a
        # Startup entry cannot, so "it is on" means different things.
        "method": "task" if task else "startup-folder" if startup else "",
        "task": TASK_NAME,
        "launcher": str(launcher_path()) if registered else "",
        # Said out loud, because this is the difference that will look like a
        # bug after the first overnight run.
        "note": ("starts when you sign in to Windows, not when the PC powers "
                 "on — the key can only be unsealed inside your session"),
    }


def register() -> dict:
    """Turn it on. Refuses without a usable key, and never demands elevation."""
    if not available():
        raise RuntimeError("unattended autostart is Windows-only on this build")
    if syskey.load() is None:
        # Fail closed and say why. A launcher that starts and finds no key
        # would exit cleanly at every logon, which looks exactly like working.
        raise RuntimeError(
            "no readable recording key — enrol one first, or this would start "
            "at every logon and immediately stop with nothing to do")
    launcher = write_launcher()

    r = _schtasks("/create", "/tn", TASK_NAME, "/tr", f'"{launcher}"',
                  "/sc", "ONLOGON", "/rl", "LIMITED", "/f")
    if r.returncode == 0:
        LOG.info("autostart registered as a logon task: %s -> %s", TASK_NAME, launcher)
        return status()

    # Denied is the ordinary case on a locked-down machine, not an error worth
    # surfacing — fall back rather than ask the user to run as administrator.
    LOG.info("logon task refused (%s); using the Startup folder instead",
             (r.stderr or r.stdout).strip()[:120])
    try:
        startup_dir().mkdir(parents=True, exist_ok=True)
        startup_entry().write_text(NL.join([
            "@echo off",
            "rem Generated by Grindstone. Delete this file, or use the toggle",
            "rem in Data management, to stop recording at logon.",
            f'call "{launcher}"',
            "",
        ]), encoding="utf-8")
    except OSError as e:
        raise RuntimeError(
            f"could not register a logon task ({(r.stderr or r.stdout).strip()[:120]}) "
            f"and could not write to the Startup folder either: {e}") from None
    LOG.info("autostart registered in the Startup folder: %s", startup_entry())
    return status()


def unregister() -> dict:
    """Turn it off — both mechanisms, and the run already in flight."""
    if not available():
        return status()
    r = _schtasks("/delete", "/tn", TASK_NAME, "/f")
    if r.returncode == 0:
        LOG.info("autostart unregistered: %s", TASK_NAME)
    # BOTH, always. Removing only the one believed to be active would leave the
    # other quietly starting a recorder the user thinks they turned off.
    startup_entry().unlink(missing_ok=True)
    launcher_path().unlink(missing_ok=True)
    # Stopping the SCHEDULE is not stopping the RUN. A recorder started at the
    # last logon is still going; the flag it checks each tick is how it learns
    # to stop, without this process needing any way to talk to it.
    try:
        (data_dir() / "recorder.stop").write_text("stop", encoding="utf-8")
    except OSError:  # a missing data dir means nothing is running anyway
        pass
    return status()
